Дана целочисленная прямоугольная матрица. Определить количество столбцов, не
содержащих ни одного нулевого элемента. Характеристикой строки целочисленной матрицы
назовем сумму ее положительных четных элементов. Переставляя строки заданной
матрицы, расположить их в соответствии с ростом характеристик.

In [2]:
import numpy as np
m = np.matrix('1 0 0 4; 5 6 7 10; 9 1 5 7')
m

matrix([[ 1,  0,  0,  4],
        [ 5,  6,  7, 10],
        [ 9,  1,  5,  7]])

In [28]:
m[m != 0] = 1
ans = m.prod(axis = 0).sum()
print(f"{ans} - количество строк без 0")

2 - количество строк без 0


In [31]:
m = np.matrix('1 0 0 4; 5 6 7 10; 9 1 5 7')
stat = m.sum(axis=1)
ans = m[stat.argsort(axis=0)]
print(ans)

[[[ 1  0  0  4]]

 [[ 9  1  5  7]]

 [[ 5  6  7 10]]]
